services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    #volumes:
    #- postgres_data:/var/lib/postgresql/data  #This should preserve data between sessions (Delete if issue)
    # TODO: Find a way to mount data so I don't have to remake a database every time (Shouldn't matter though since docker takes snapshots (I think))
  blog:
    build: .
    environment:
      FLASK_APP: "blog:create_app"
      FLASK_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_DEV_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./blog:/personal-flask-blog/blog #auto reload
